name: leadmanager
description: "A new Flutter project."
publish_to: "none"

version: 1.1.0+16

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  loading_animation_widget: ^1.3.0
  flutter_dotenv: ^5.2.1
  dio: ^5.8.0+1
  provider: ^6.1.5
  flutter_secure_storage: ^9.2.4
  flash: ^3.1.1
  flutter_launcher_icons: ^0.14.4
  package_info_plus: ^8.3.0
  infinite_scroll_pagination: ^5.1.0
  intl: ^0.20.2
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  # adaptive_icon_background: "#643CB5"
  adaptive_icon_foreground: "assets/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
